%% calculate the sensitivity of additional variables
clear all
% main
load('Results\main')  % can directly load solution; otherwise, run main.m

addition_sen_data = [0.386, -0.024, -0.001, -2.491, -1.949, -3.195, -1.232, -2.587];

addition_sen = [simu_un0.reg_srd;...
                          simu_un0.reg_sr;...
                          0;...
                          simu_un0.reg_D;...
                          simu_un0.reg_B_agg; ...
                         -simu_un0.reg_N; ...
                          simu_un0.reg_G1; ...       
                          simu_un0.reg_A1];
                      
save("Results\T5_Reponsiveness",'addition_sen_data','addition_sen')
load("Results\T5_Reponsiveness")

disp([addition_sen_data', addition_sen,])
